### ISSUE TITLE
Unable to install generator

### ISSUE THREAD

**Issue by singh-** [thardy/generator-ngbp#17]
While running "npm install -g generator-ngbp" get this error:

E:\wamp\www\angular\>npm install -g generator-ngbp
npm WARN peerDependencies The peer dependency yo@>=1.0.0 included from generator-ngbp will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
generator-ngbp@0.1.5 C:\Program Files\nodejs\node_modules\generator-ngbp
├── chalk@0.4.0 (has-color@0.1.7, ansi-styles@1.0.0, strip-ansi@0.1.1)
├── touch@0.0.3 (nopt@1.0.10)
└── yeoman-generator@0.16.0 (dargs@0.1.0, debug@0.7.4, diff@1.0.8, class-extend@0.1.1, rimraf@2.2.8, findup-sync@0.1.3, text-table@0.2.0, mime@1.2.11, async@0.2.10, mkdirp@0.3.5, isbinaryfile@2.0.3, s
helljs@0.2.6, iconv-lite@0.2.11, underscore.string@2.3.3, lodash@2.4.1, glob@3.2.11, request@2.30.0, file-utils@0.1.5, cheerio@0.13.1, inquirer@0.4.1, download@0.1.19)

Since it gave a warning but no error, I tried running the generator, but got a message that it's not installed!

E:\wamp\www\angular\ui-router-eg>yo ngbp
Error ngbp

You don't seem to have a generator with the name ngbp installed.

What have I tried?
- Updated node from ver# 0.10.x to ver# 0.12.0
- tried uninstalling and re-installing:
   - yo
   - grunt-cli

but to no success. What am I missing?

**Comment by thardy** [comment]
I tried to reproduce this but was unable to.  I uninstalIed generator-ngbp and reinstalled.  I didn't get the warning with node 0.10.30 and yo 1.3.3, and the generator worked fine.  I then installed the latest node - 0.12.2 and updated yo to 1.4.6, and I got the warning, but the generator still worked fine.

I will look into removing that warning this weekend by moving the yo dependency from peer to a direct dependency, but I'm thinking your issue lies elsewhere.  

Here's what I would try:
- can you install and successfully run other generators?
- if you're using a console, do you need to close and re-open that console (sometimes paths don't get updated until you re-open, especially after a big install like node)
- Confirm that the generator is actually getting installed (which would mean you've got a path issue).  On Windows 7 mine gets installed to C:\Users\<username>\AppData\Roaming\npm\node_modules\generator-ngbp

Let me know what you find.

**Comment by thardy** [comment]
I just pushed a new version with a pull request I received and I also fixed that warning.  You shouldn't get it anymore.

**Comment by singh-** [comment]
It was an issue with node installation. I found the presence of node at 2 places: C:\Users\username\AppData\Roaming\npm\node_modules\
and
C:\Program FIles\nodejs\node_modules

Not sure how this happened, but uninstalling and reinstalling node helped.

Thanks a lot for you feedback.
